const conditionCode = {
	0:	"tornado",
	1:	"tropical storm",
	2:	"hurricane",
	3:	"severe thunderstorms",
	4:	"thunderstorms",
	5:	"mixed rain and snow",
	6:	"mixed rain and sleet",
	7:	"mixed snow and sleet",
	8:	"freezing drizzle",
	9:	"drizzle",
	10:	"freezing rain",
	11:	"showers",
	12:	"rain",
	13:	"snow flurries",
	14:	"light snow showers",
	15:	"blowing snow",
	16:	"snow",
	17:	"hail",
	18:	"sleet",
	19:	"dust",
	20:	"foggy",
	21:	"haze",
	22:	"smoky",
	23:	"blustery",
	24:	"windy",
	25:	"cold",
	26:	"cloudy",
	27:	"mostly cloudy (night)",
	28:	"mostly cloudy (day)",
	29:	"partly cloudy (night)",
	30:	"partly cloudy (day)",
	31:	"clear (night)",
	32:	"sunny",
	33:	"fair (night)",
	34:	"fair (day)",
	35:	"mixed rain and hail",
	36:	"hot",
	37:	"isolated thunderstorms",
	38:	"scattered thunderstorms",
	39:	"scattered showers (day)",
	40:	"heavy rain",
	41:	"scattered snow showers (day)",
	42:	"heavy snow",
	43:	"blizzard",
	44:	"not available",
	45:	"scattered showers (night)",
	46:	"scattered snow showers (night)",
	47:	"scattered thundershowers"
}
// get moon cloud, heavy rain and showers 
const svg = {
    0: "weather_hurricane_storm_tornado_icon.svg",
    1: "weather_clouds_night_storm_icon.svg",
    2: "weather_hurricane_storm_tornado_icon.svg",
    3: "weather_clouds_night_storm_icon.svg",
    4: "weather_clouds_night_storm_icon.svg",
    5: "weather_moon_moonlight_night_icon.svg",
    6: "weather_cloud_drizzel_rain_icon.svg",
    7: "weather_moon_moonlight_night_icon.svg",
    8: "weather_cloud_drizzel_rain_icon.svg",
    9: "weather_cloud_drizzel_rain_icon.svg",
    10: "weather_cloud_drizzel_rain_icon.svg",
    11: "weather_cloud_drizzel_rain_icon.svg",
    12: "weather_cloud_drizzel_rain_icon.svg",
    13: "weather_christmas_snow_snowflake_winter_icon.svg",
    14: "weather_christmas_snow_snowflake_winter_icon.svg",
    15: "weather_snow_snowflake_winter_freeze_icon.svg",
    16: "weather_snow_snowflake_winter_freeze_icon.svg",
    17: "weather_clouds_hail_hailstone_snow_icon.svg",
    18: "weather_clouds_hail_hailstone_snow_icon.svg",
    19: "weather_day_sand_sandstorm_sun_icon.svg",
    20: "weather_clouds_cloudy_fog_foggy_icon.svg",
    21: "weather_clouds_cloudy_fog_foggy_icon.svg",
    22: "weather_clouds_cloudy_fog_foggy_icon.svg",
    23: "weather_clouds_cloudy_fog_foggy_icon.svg",
    24: "weather_clouds_hail_hailstone_snow_icon.svg",
    25: "weather_christmas_snow_snowflake_winter_icon.svg",
    26: "weather_cloud_clouds_cloudy_icon.svg",
    27: "weather_cloud_clouds_cloudy_icon.svg",
    28: "weather_clouds_sun_sunny_icon.svg",
    29: "weather_cloud_clouds_cloudy_icon.svg",
    30: "weather_clouds_sun_sunny_icon.svg",
    31: "weather_moon_moonlight_night_icon.svg",
    32: "weather_sun_sunny_temperature_icon.svg",
    33: "weather_moon_moonlight_night_icon.svg",
    34: "weather_sun_sunny_temperature_icon.svg",
    35: "weather_cloud_drizzel_rain_icon.svg",
    36: "weather_sun_sunny_temperature_icon.svg",
    37: "weather_clouds_night_storm_icon.svg",
    38: "weather_clouds_night_storm_icon.svg",
    39: "weather_cloud_drizzel_rain_icon.svg",
    40: "weather_cloud_drizzel_rain_icon.svg",
    41: "weather_christmas_snow_snowflake_winter_icon.svg",
    42: "weather_snow_snowflake_winter_freeze_icon.svg",
    43: "weather_snow_snowflake_winter_freeze_icon.svg",
    45: "weather_cloud_drizzel_rain_icon.svg",
    46: "weather_moon_night_snow_icon.svg",
    47: "weather_cloud_thunder_rain_icon.svg",
}

const weiodData = {
	"Select your city": null,
    "London": 44418,
    "Berlin": 638243,
    "Madrid": 766273,
    "Rome": 721943,
    "Paris": 615702,
    "Moscow": 2122265,
    "Istanbul": 2344116,
    "Warsaw": 523920,
    "Vienna": 551801,
    "Prague": 796597,
    "Sydney": 1105779,
    "Melbourne": 1103816,
    "Brisbane": 1100661,
    "Perth": 1098081,
    "Adelaide": 1099805,
    "Bangkok": 1225448,
    "New Delhi": 2295019,
    "Mumbai": 2295411,
    "Kuala Lumpur": 1154781,
    "Hanoi": 1236594,
    "Islamabad": 2211027,
    "Cape Town": 1591691,
    "Johannesburg": 1582504,
    "Lagos": 1398823,
    "Nairobi": 1528488,
    "Afghanistan": 23424739,
    "Algeria": 23424740,
    "American Samoa": 23424746,
    "Andorra": 23424744,
    "Angola": 23424745,
    "Anguilla": 23424751,
    "Antarctica": 28289409,
    "Antigua and Barbuda": 23424737,
    "Argentina": 23424747,
    "Armenia": 23424743,
    "Aruba": 23424736,
    "Australia": 23424748,
    "Azerbaijan": 23424741,
    "Bangladesh": 23424759,
    "Barbados": 23424754,
    "Belarus": 23424765,
    "Belgium": 23424757,
    "Belize": 23424760,
    "Benin": 23424764,
    "Bermuda": 23424756,
};


const category	= {
	Business: "Business",
	Entertainment: "Entertainment",
	Health: "Health",
	Politics: "Politics",
	Products: "Products",
	"Science And Technology": "ScienceAndTechnology",
	Technology: "Technology",
	Science: "Science",
	Sports: "Sports",
	US: "US",
	World: "World",
	Africa: "World_Africa",
	Americas: "World_Americas",
	Asia: "World_Asia",
	Europe: "World_Europe",
	MiddleEast: "World_MiddleEast"
}


export { conditionCode, svg, weiodData, category };